apiVersion: v1
kind: Service
metadata:
  name: mock-server
  labels:
    app: mock-server
    tier: mock
    framework: express
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: mock-server